# Generated by Django 4.0 on 2021-12-17 16:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', tinymce.models.HTMLField()),
                ('estado', models.IntegerField(choices=[(1, 'Artículo Activo'), (2, 'Artículo Inactivo')], default=1)),
                ('visibilidad', models.IntegerField(choices=[(1, 'Visible - Publica'), (2, 'Borrador - Privada')], default=1)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articulos',
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'etiquetas',
                'ordering': ['nombre'],
            },
        ),
    ]
