# Generated by Django 4.0 on 2021-12-14 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('articulos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria'),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='etiquetas',
        ),
        migrations.AddField(
            model_name='articulo',
            name='etiquetas',
            field=models.ManyToManyField(to='articulos.Etiquetas'),
        ),
    ]
