# Generated by Django 4.0 on 2021-12-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_remove_articulo_categoria_articulo_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etiquetas',
            new_name='Etiqueta',
        ),
    ]
