# Generated by Django 4.0 on 2021-12-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_rename_etiquetas_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='visibilidad',
            field=models.BooleanField(default=False),
        ),
    ]
