# Generated by Django 4.0 on 2021-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_alter_articulo_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Artículo Activo'), (2, 'Artículo Inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='visibilidad',
            field=models.IntegerField(choices=[(1, 'Visible - Publica'), (2, 'Borrador - Privada')], default=1),
        ),
    ]
