# Generated by Django 4.0 on 2021-12-16 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_estado'),
        ('articulos', '0006_alter_articulo_estado_alter_articulo_visibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
