# Generated by Django 4.0 on 2021-12-17 00:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
