# Generated by Django 4.0 on 2021-12-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_autor'),
        ('usuarios', '0004_alter_usuario_estado'),
        ('comentarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
