# Generated by Django 4.0 on 2021-12-17 00:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_alter_comentario_articulo_alter_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
