# Generated by Django 4.0 on 2021-12-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_apellido_remove_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
