# Generated by Django 4.0 on 2021-12-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Usuario Activo'), (2, 'Usuario Inactivo - Bloqueado')], default=1),
        ),
    ]
