# Generated by Django 4.0 on 2021-12-17 00:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
